# Generated by Django 4.1.6 on 2023-02-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("C1", "Category1"),
                            ("C2", "Category2"),
                            ("C3", "Category3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("price_day_1", models.IntegerField()),
                ("price_day_3", models.IntegerField()),
                ("price_day_10", models.IntegerField()),
                ("student_promotion", models.IntegerField()),
            ],
        ),
    ]
