# Generated by Django 4.1.6 on 2023-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=200, null=True)),
                ("city", models.CharField(max_length=200, null=True)),
                ("region", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("personal", "personal"),
                            ("business", "business"),
                            ("student", "student"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Category1", "Category1"),
                            ("Category2", "Category2"),
                            ("Category3", "Category3"),
                        ],
                        max_length=200,
                    ),
                ),
                ("year", models.IntegerField()),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Category3", "Category3"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_day_1",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_day_10",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_day_3",
            field=models.FloatField(),
        ),
    ]
