# Generated by Django 4.1.6 on 2023-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_client_video_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
