# Generated by Django 4.1.6 on 2023-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_video_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Camera Video", "Camera Video"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Comecials", "Comecials"),
                ],
                max_length=200,
            ),
        ),
    ]
