# Generated by Django 4.1.6 on 2023-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_product_category_alter_video_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_day_1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_day_10",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_day_3",
            field=models.IntegerField(),
        ),
    ]
