# Generated by Django 4.1.6 on 2023-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0008_alter_product_price_day_1_alter_product_price_day_10_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="order_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
