# Generated by Django 4.1.6 on 2023-02-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_reservation_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="duration",
        ),
        migrations.AddField(
            model_name="reservation",
            name="order_hour",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="client_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
