# Generated by Django 4.1.6 on 2023-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_remove_reservation_duration_reservation_order_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_sent",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
