# Generated by Django 4.1.6 on 2023-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_remove_message_date_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_sent",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
