# Generated by Django 4.1.6 on 2023-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_message_date_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
