# Generated by Django 4.1.6 on 2023-02-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_client_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
