# Generated by Django 4.1.6 on 2023-02-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_product_short_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="short_description",
            new_name="summary",
        ),
    ]
