# Generated by Django 4.1.6 on 2023-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_rename_short_description_product_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
