# Generated by Django 4.1.6 on 2023-02-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_video_thumbnail_video_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video",
        ),
    ]
