# Generated by Django 4.1.6 on 2023-02-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_remove_video_thumbnail_remove_video_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="client_name",
            new_name="client",
        ),
    ]
