# Generated by Django 4.1.6 on 2023-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_rename_client_name_video_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
