# Generated by Django 4.1.6 on 2023-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_alter_video_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
