# Generated by Django 4.1.6 on 2023-02-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_showreel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showreel",
            old_name="image",
            new_name="thumbnail",
        ),
    ]
