# Generated by Django 4.1.6 on 2023-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0026_rename_image_showreel_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="client",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
        migrations.AddField(
            model_name="message",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="client_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="client_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="client_prefix",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_prefix",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "personal"),
                    ("business", "business"),
                    ("student", "student"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
