# Generated by Django 4.1.6 on 2023-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0028_client_remove_message_client_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="client_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
