# Generated by Django 4.1.6 on 2023-02-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0032_delete_client_reservation_client_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="client_city",
            new_name="client_business",
        ),
    ]
