# Generated by Django 4.1.6 on 2023-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0033_rename_client_city_reservation_client_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Comercials", "Comercials"),
                ],
                max_length=200,
            ),
        ),
    ]
