# Generated by Django 4.1.6 on 2023-03-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0034_alter_video_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="read",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
