# Generated by Django 4.1.6 on 2023-03-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0035_reservation_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="read",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "personal"),
                    ("business", "business"),
                    ("student", "student"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
