# Generated by Django 4.1.6 on 2023-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0036_alter_reservation_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="read",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
