# Generated by Django 4.1.6 on 2023-03-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0037_alter_reservation_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Commercials", "Commercials"),
                ],
                max_length=200,
            ),
        ),
    ]
