# Generated by Django 4.1.6 on 2023-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0038_alter_video_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
    ]
