# Generated by Django 4.1.6 on 2023-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0039_product_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
