# Generated by Django 4.1.6 on 2023-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0040_message_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_time_sent",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
