# Generated by Django 4.1.6 on 2023-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0041_message_date_time_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(upload_to=""),
        ),
    ]
