# Generated by Django 4.1.6 on 2023-03-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0042_alter_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="client",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
