# Generated by Django 4.1.6 on 2023-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0043_message_client_city_alter_video_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Camera Video", "Camera Video"),
                    ("Image", "Image"),
                ],
                max_length=200,
            ),
        ),
    ]
