# Generated by Django 4.1.6 on 2023-03-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0044_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.product",
            ),
        ),
    ]
