# Generated by Django 4.1.6 on 2023-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0045_alter_reservation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Image", "Image"),
                    ("Lightning", "Lightning"),
                    ("Support", "Support"),
                    ("Sound", "Sound"),
                ],
                max_length=200,
            ),
        ),
    ]
