# Generated by Django 4.1.6 on 2023-03-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0050_message_date_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Image", "Image"),
                    ("Lighting", "Lighting"),
                    ("Support", "Support"),
                    ("Sound", "Sound"),
                ],
                max_length=200,
            ),
        ),
    ]
